In [ ]:
# From lists or tuples:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

#Using built-in functions
zeroes_arr=np.zeros((3,3))
print(zeroes_arr)

ones_arr=np.ones((2,2))
print(ones_arr)

#Arange and linspace
arrnew=np.arange(0,10,2)
print(arrnew)

lin_arr=np.linspace(0,1,5)
print(lin_arr)

#Random Arrays
ran_arr=np.random.rand(3,3)
print(ran_arr)

In [1]:
# Calculation using Arrays
import numpy as np
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[11 22 33]
[10 40 90]
[ 9 18 27]
[10. 10. 10.]


In [2]:
# Mean,median and standard deviation
import numpy as np
data = [10, 20, 30, 40, 50]
print("Mean:", np.mean(data))
print("median:", np.median(data))
print("Standard deviation:", np.std(data))

Mean: 30.0
median: 30.0
Standard deviation: 14.142135623730951
